### ISSUE TITLE
Testy

### ISSUE THREAD

**Issue by krzepka** [kklipski/ALHE-projekt#5]
Dla sieci z zadanymi parametrami powtórzyć testy kilka razy i liczyć odchylenie standardowe.

**Comment by kklipski** [comment]
- [x] standardowe TD3 (z ograniczeniem ilości kroków bez ruchu oraz karami za zatrzymywanie się i utykanie w miejscu) - @krzepka 
- [x] parametry: n_networks = 5, saved_scores = 5, episodes_ready = [5, 7, 10, 15, 20], explore_prob = 0.05, explore_factors = [0.99, 1.01] - @krzepka 
- [x] parametry: n_networks = 5, saved_scores = 10, episodes_ready = [10, 15, 20, 25, 30], explore_prob = 0.5, explore_factors = [0.95, 1.05] - @kklipski 
- [x] parametry: n_networks = 10, saved_scores = 10, episodes_ready = [10, 11, 12, 13, 14, 15, 16, 20, 25, 30], explore_prob = 0.5, explore_factors = [0.95, 1.05] - @kklipski
- [x] parametry: n_networks = 5, saved_scores = 10, episodes_ready = [10, 15, 20, 25, 30], explore_prob = 0.05, explore_factors = [0.99, 1.01] - @kklipski 
- [x] parametry: n_networks = 10, saved_scores = 10, episodes_ready = [10, 11, 12, 13, 14, 15, 16, 20, 25, 30], explore_prob = 0.05, explore_factors = [0.99, 1.01] - @krzepka
