### ISSUE TITLE
Punkty ujemne dla stania w miejscu

### ISSUE THREAD

**Issue by krzepka** [kklipski/ALHE-projekt#8]
Sieć 1: robot cały czas staje w miejscu, średni wynik z 10 to jakieś -30
Sieć 2: robot robi kilkanaście kroków i się wywala, średni wynik to -60
Wagi z 1 skopiują się do 2...

Zobaczmy jak to wyjdzie bo może to nie będzie problem, ale być może trzeba będzie zrobić i przetestować drugi tryb, w którym robot będzie dostawał sporo punktów ujemnych

**Comment by kklipski** [comment]
Testuję takie rozwiązanie.

**Comment by kklipski** [comment]
Done.
